In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd

In [ ]:
iris = load_iris()

In [ ]:
iris_data = iris.data

In [ ]:
iris_label = iris.target

In [ ]:
print('iris target값: ', iris_label)

iris target값:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
print('iris target명: ', iris.target_names)

iris target명:  ['setosa' 'versicolor' 'virginica']


In [ ]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

In [ ]:
iris_df ['label'] = iris.target

In [ ]:
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [ ]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [ ]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [ ]:
y_pred = dt_clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print('예측정확도 : {0: .4f}'.format(accuracy_score(y_test, y_pred)))

예측정확도 :  0.9333


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
features = iris.data

In [ ]:
label = iris.target

In [ ]:
dt_clf = DecisionTreeClassifier(random_state=156)

In [ ]:
kfold = KFold(n_splits=5)

In [ ]:
cv_accuracy = []

In [ ]:
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [ ]:
n_iter = 0

In [ ]:
for train_index, test_index in kfold.split(features):

    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]


    dt_clf.fit(X_train, y_train)


    pred = dt_clf.predict(X_test)


    accuracy = np.round(accuracy_score(y_test, pred), 4)
    cv_accuracy.append(accuracy)
    n_iter += 1

    print(f"교차 검증 {n_iter} 정확도: {accuracy}")

교차 검증 6 정확도: 1.0
교차 검증 7 정확도: 1.0
교차 검증 8 정확도: 0.8333
교차 검증 9 정확도: 0.9333
교차 검증 10 정확도: 0.8


In [ ]:
print(f"평균 교차 검증 정확도: {np.mean(cv_accuracy)}")

평균 교차 검증 정확도: 0.9


In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
iris = load_iris()

In [ ]:
X = iris.data

In [ ]:
y = iris.target

In [ ]:
n_iterations = 100

In [ ]:
n_size = int(len(X) * 0.8)

In [ ]:
dt_clf = DecisionTreeClassifier(random_state=42)


In [ ]:
accuracies = []

In [ ]:
for i in range(n_iterations):

    indices = np.random.choice(len(X), n_size, replace=True)
    X_train = X[indices]
    y_train = y[indices]


    mask = np.ones(len(X), dtype=bool)
    mask[indices] = False
    X_test = X[mask]
    y_test = y[mask]


    dt_clf.fit(X_train, y_train)


    pred = dt_clf.predict(X_test)


    accuracy = accuracy_score(y_test, pred)
    accuracies.append(accuracy)

In [ ]:
mean_accuracy = np.mean(accuracies)
print(f"평균 부트스트래핑 정확도: {mean_accuracy:.4f}")

평균 부트스트래핑 정확도: 0.9428


In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
iris = load_iris()

In [ ]:
x_train = iris.data[:-30]

In [ ]:
y_train = iris.target[:-30]

In [ ]:
x_test = iris.data[-30:]

In [ ]:
y_test = iris.target[-30:]

In [ ]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]


In [ ]:
print(y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(n_estimators=10)

In [ ]:
rfc

RandomForestClassifier(n_estimators=10)

In [ ]:
rfc.fit(x_train, y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
prediction = rfc.predict(x_test)

In [ ]:
print(prediction==y_test)

[ True False  True False  True  True False False  True False  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]


In [ ]:
rfc.score(x_test, y_test)

0.7333333333333333

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print("Accuracy is: ", accuracy_score(prediction, y_test))

Accuracy is:  0.7333333333333333


In [ ]:
print(classification_report(prediction, y_test))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         8
           2       0.73      1.00      0.85        22

    accuracy                           0.73        30
   macro avg       0.37      0.50      0.42        30
weighted avg       0.54      0.73      0.62        30



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = iris.data

In [ ]:
y = iris.target

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
print(y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
print(Y_test)

[0 2 2 1 1 2 1 2 0 2 0 2 1 1 2 2 0 2 1 0 1 2 0 1 0 2 0 2 2 1]


In [ ]:
clf = RandomForestClassifier(n_estimators=10)

In [ ]:
clf.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
prediction_1 = rfc.predict(X_test)

In [ ]:
print("Accuracy is: ", accuracy_score(prediction_1, Y_test))

Accuracy is:  0.9666666666666667


In [ ]:
print(classification_report(prediction_1, Y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.90      0.95        10
           2       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
iris = load_iris()

In [ ]:
X = iris.data

In [ ]:
y = iris.target

In [ ]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)


In [ ]:
rf_clf = RandomForestClassifier(random_state=42)

In [ ]:
n_iter = 0

In [ ]:
cv_accuracy = []


In [ ]:
for train_index, test_index in kf.split(X):

    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]


    rf_clf.fit(X_train, y_train)


    pred = rf_clf.predict(X_test)


    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    n_iter += 1

    print(f"교차 검증 {n_iter} 정확도: {accuracy:.4f}")

교차 검증 1 정확도: 1.0000
교차 검증 2 정확도: 0.9667
교차 검증 3 정확도: 0.9333
교차 검증 4 정확도: 0.9333
교차 검증 5 정확도: 0.9667


In [ ]:
print(f"평균 교차 검증 정확도: {np.mean(cv_accuracy):.4f}")

평균 교차 검증 정확도: 0.9600


In [ ]:
import numpy as np

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
iris = load_iris()

In [ ]:
X = iris.data

In [ ]:
y = iris.target

In [ ]:
n_iterations = 100

In [ ]:
n_size = int(len(X) * 0.8)

In [ ]:
rf_clf = RandomForestClassifier(random_state=42)

In [ ]:
accuracies = []


In [ ]:
for i in range(n_iterations):

    indices = np.random.choice(len(X), n_size, replace=True)
    X_train = X[indices]
    y_train = y[indices]


    mask = np.ones(len(X), dtype=bool)
    mask[indices] = False
    X_test = X[mask]
    y_test = y[mask]


    rf_clf.fit(X_train, y_train)


    pred = rf_clf.predict(X_test)


    accuracy = accuracy_score(y_test, pred)
    accuracies.append(accuracy)

In [ ]:
mean_accuracy = np.mean(accuracies)
print(f"평균 부트스트래핑 정확도: {mean_accuracy:.4f}")

평균 부트스트래핑 정확도: 0.9455
